//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by Tasking.rc
//
#define IDD_ABOUTBOX                    100
#define IDD_TASKING_FORM                101
#define IDR_MAINFRAME                   128
#define IDR_TASKINTYPE                  129
#define IDC_CBONIDLE1                   1000
#define IDC_CBONIDLE2                   1001
#define IDC_CBTHREAD1                   1002
#define IDC_CBTHREAD2                   1003

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_3D_CONTROLS                     1
#define _APS_NEXT_RESOURCE_VALUE        130
#define _APS_NEXT_COMMAND_VALUE         32771
#define _APS_NEXT_CONTROL_VALUE         1004
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
