all:
	cd common && make
	cd errors && make
	cd process && make
	cd exec && make
	cd signals && make
clean:
	cd common && make clean
	cd errors && make clean
	cd process && make clean
	cd exec && make clean
	cd signals && make clean
	