//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by day10.rc
//
#define IDD_ABOUTBOX                    100
#define IDR_MAINFRAME                   128
#define IDR_DAY10TYPE                   129
#define ID_COLOR_BLACK                  32771
#define ID_COLOR_BLUE                   32772
#define ID_COLOR_GREEN                  32773
#define ID_COLOR_CYAN                   32774
#define ID_COLOR_RED                    32775
#define ID_COLOR_MAGENTA                32776
#define ID_COLOR_YELLOW                 32777
#define ID_COLOR_WHITE                  32778
#define ID_COLOR                        32779

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_3D_CONTROLS                     1
#define _APS_NEXT_RESOURCE_VALUE        130
#define _APS_NEXT_COMMAND_VALUE         32780
#define _APS_NEXT_CONTROL_VALUE         1000
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
