all:
	cd linux_unleashed && make
	cd unix_gestionarea_proceselor && make
	cd real-time_Embedded_Systems && make
clean:
	cd linux_unleashed && make clean
	cd unix_gestionarea_proceselor && make clean
	cd real-time_Embedded_Systems && make clean

