all:
	cd rdir && make
	cd rcat && make
	cd hangman && make
	cd warehouse && make
	cd watchaccess && make
	cd rpc && make
	
clean:
	cd rdir && make clean
	cd rcat && make clean
	cd hangman && make clean
	cd warehouse && make clean
	cd watchaccess && make clean
	cd rpc && make clean