program operatii_cu_intregi;
begin
	writeln('1 shl 2 =', 1 shl 2);
   writeln('8 shr 2 =', 8 shr 2);
   writeln;
   writeln('not 0 =', not 0);
	writeln;
   writeln('1 and 0 =', 1 and 0);
   writeln('1 and 1 =', 1 and 1);
   writeln('1 or 0 =', 1 or 0);
   writeln('1 or 1 =', 1 or 1);
   writeln('1 xor 0 =', 1 xor 0);
   writeln('1 xor 1 =', 1 xor 1);
   writeln;
   writeln('3 and 1 or 0 =', 3 and 1 or 0);
   writeln('3 or 1 and 0 =', 3 or 1 and 0);
end.