all:
	cd iorutines && make
	cd process && make
	cd errors && make
	cd memory && make
	cd ipc && make
	cd libs && make
	cd graphics && make
clean:
	cd iorutines && make clean
	cd process && make clean
	cd errors && make clean
	cd memory && make clean
	cd ipc && make clean
	cd libs && make clean
	cd graphics && make clean
	