all:
	cd exec && make
	cd file && make
	cd pipe && make
	cd fifo && make
	cd msg && make
clean:
	cd exec && make clean
	cd file && make clean
	cd pipe && make clean
	cd fifo && make clean
	cd msg && make clean
	